"""revision-0_6

Revision ID: 237031a776fb
Revises: d3db4a1a7f75
Create Date: 2021-02-04 11:01:54.703210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '237031a776fb'
down_revision = 'd3db4a1a7f75'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_systems', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='lccs')
    op.alter_column('class_systems', 'version',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='lccs')
    op.alter_column('classes', 'class_system_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='lccs')
    op.alter_column('classes', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='lccs')
    op.add_column('styles', sa.Column('mime_type', sa.Text(), nullable=False), schema='lccs')
    op.drop_column('styles', 'style', schema='lccs')
    op.add_column('styles', sa.Column('style', sa.LargeBinary(), nullable=False), schema='lccs')
    op.create_index(op.f('idx_lccs_styles_mime_type'), 'styles', ['mime_type'], unique=False, schema='lccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_lccs_styles_mime_type'), table_name='styles', schema='lccs')
    op.drop_column('styles', 'style', schema='lccs')
    op.add_column('styles', sa.Column('style', sa.JSON(), nullable=True), schema='lccs')
    op.drop_column('styles', 'mime_type', schema='lccs')
    op.alter_column('classes', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='lccs')
    op.alter_column('classes', 'class_system_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='lccs')
    op.alter_column('class_systems', 'version',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='lccs')
    op.alter_column('class_systems', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='lccs')
    # ### end Alembic commands ###
