"""Update class name limit.

Revision ID: 54986ade6947
Revises: 561ebe6266ad
Create Date: 2023-10-23 08:47:10.551892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54986ade6947'
down_revision = '561ebe6266ad'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=64),
               existing_comment='Class name internally.',
               existing_nullable=False,
               schema='lccs')
    op.alter_column('classification_systems', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='Classification System name internally.',
               existing_nullable=False,
               schema='lccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classification_systems', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='Classification System name internally.',
               existing_nullable=False,
               schema='lccs')
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='Class name internally.',
               existing_nullable=False,
               schema='lccs')
    # ### end Alembic commands ###
