"""internationalization

Revision ID: 561ebe6266ad
Revises: 83db828c55ad
Create Date: 2021-08-17 15:56:57.186232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '561ebe6266ad'
down_revision = '83db828c55ad'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('title_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='A human-readable string naming for class.'), schema='lccs')
    op.add_column('classes', sa.Column('description_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True), schema='lccs')
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=32),
               comment='Class name internally.',
               existing_nullable=False,
               schema='lccs')
    op.create_index(op.f('idx_lccs_classes_description_translations'), 'classes', ['description_translations'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_title_translations'), 'classes', ['title_translations'], unique=False, schema='lccs')
    op.drop_column('classes', 'description', schema='lccs')
    op.add_column('classification_systems', sa.Column('title_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='A human-readable string naming for classification system.'), schema='lccs')
    op.add_column('classification_systems', sa.Column('description_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True), schema='lccs')
    op.alter_column('classification_systems', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=32),
               comment='Classification System name internally.',
               existing_nullable=False,
               schema='lccs')
    op.create_index(op.f('idx_lccs_classification_systems_description_translations'), 'classification_systems', ['description_translations'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classification_systems_title_translations'), 'classification_systems', ['title_translations'], unique=False, schema='lccs')
    op.drop_column('classification_systems', 'description', schema='lccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_systems', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False), schema='lccs')
    op.drop_index(op.f('idx_lccs_classification_systems_title_translations'), table_name='classification_systems', schema='lccs')
    op.drop_index(op.f('idx_lccs_classification_systems_description_translations'), table_name='classification_systems', schema='lccs')
    op.alter_column('classification_systems', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Classification System name internally.',
               existing_nullable=False,
               schema='lccs')
    op.drop_column('classification_systems', 'description_translations', schema='lccs')
    op.drop_column('classification_systems', 'title_translations', schema='lccs')
    op.add_column('classes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False), schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_title_translations'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_description_translations'), table_name='classes', schema='lccs')
    op.alter_column('classes', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Class name internally.',
               existing_nullable=False,
               schema='lccs')
    op.drop_column('classes', 'description_translations', schema='lccs')
    op.drop_column('classes', 'title_translations', schema='lccs')
    # ### end Alembic commands ###