""" create-initial-tables

Revision ID: 7661f3f76beb
Revises: 
Create Date: 2020-03-05 14:00:36.898260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7661f3f76beb'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications_style',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('file', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='lccs'
    )
    op.create_table('class_systems',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('authority_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='lccs'
    )
    op.create_table('classes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_system_id'], ['lccs.class_systems.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='lccs'
    )
    op.create_table('style',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('class_system_id', sa.Integer(), nullable=False),
    sa.Column('application_style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_style_id'], ['lccs.applications_style.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['class_system_id'], ['lccs.class_systems.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('class_system_id', 'application_style_id'),
    schema='lccs'
    )
    op.create_table('class_mappings',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_class_id', sa.Integer(), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('degree_of_similarity', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['source_class_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['target_class_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('source_class_id', 'target_class_id'),
    schema='lccs'
    )
    op.create_table('parent_classes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('class_parent_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['class_parent_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('class_parent_id', 'class_id'),
    schema='lccs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_classes', schema='lccs')
    op.drop_table('class_mappings', schema='lccs')
    op.drop_table('style', schema='lccs')
    op.drop_table('classes', schema='lccs')
    op.drop_table('class_systems', schema='lccs')
    op.drop_table('applications_style', schema='lccs')
    # ### end Alembic commands ###
