"""add_index

Revision ID: d3db4a1a7f75
Revises: e8b12ba52665
Create Date: 2021-01-29 09:19:44.471466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3db4a1a7f75'
down_revision = 'e8b12ba52665'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_lccs_class_mappings_source_class_id'), 'class_mappings', ['source_class_id'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_class_mappings_target_class_id'), 'class_mappings', ['target_class_id'], unique=False, schema='lccs')
    op.drop_constraint('class_mappings_target_class_id_classes_fkey', 'class_mappings', schema='lccs', type_='foreignkey')
    op.drop_constraint('class_mappings_source_class_id_classes_fkey', 'class_mappings', schema='lccs', type_='foreignkey')
    op.create_foreign_key(op.f('class_mappings_source_class_id_classes_fkey'), 'class_mappings', 'classes', ['source_class_id'], ['id'], source_schema='lccs', referent_schema='lccs', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('class_mappings_target_class_id_classes_fkey'), 'class_mappings', 'classes', ['target_class_id'], ['id'], source_schema='lccs', referent_schema='lccs', onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('class_systems_name_key'), 'class_systems', ['name', 'version'], schema='lccs')
    op.create_index(op.f('idx_lccs_class_systems_name'), 'class_systems', ['name'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_class_system_id'), 'classes', ['class_system_id'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_code'), 'classes', ['code'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_name'), 'classes', ['name'], unique=False, schema='lccs')
    op.drop_constraint('classes_class_parent_id_classes_fkey', 'classes', schema='lccs', type_='foreignkey')
    op.drop_constraint('classes_class_system_id_class_systems_fkey', 'classes', schema='lccs', type_='foreignkey')
    op.create_foreign_key(op.f('classes_class_system_id_class_systems_fkey'), 'classes', 'class_systems', ['class_system_id'], ['id'], source_schema='lccs', referent_schema='lccs', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('classes_class_parent_id_classes_fkey'), 'classes', 'classes', ['class_parent_id'], ['id'], source_schema='lccs', referent_schema='lccs', onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('idx_lccs_style_formats_name'), 'style_formats', ['name'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_styles_class_system_id'), 'styles', ['class_system_id'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_styles_style_format_id'), 'styles', ['style_format_id'], unique=False, schema='lccs')
    op.drop_constraint('styles_style_format_id_style_formats_fkey', 'styles', schema='lccs', type_='foreignkey')
    op.drop_constraint('styles_class_system_id_class_systems_fkey', 'styles', schema='lccs', type_='foreignkey')
    op.create_unique_constraint(op.f('style_formats_name_key'), 'style_formats', ['name'], schema='lccs')
    op.create_foreign_key(op.f('styles_style_format_id_style_formats_fkey'), 'styles', 'style_formats', ['style_format_id'], ['id'], source_schema='lccs', referent_schema='lccs', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('styles_class_system_id_class_systems_fkey'), 'styles', 'class_systems', ['class_system_id'], ['id'], source_schema='lccs', referent_schema='lccs', onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('styles_class_system_id_class_systems_fkey'), 'styles', schema='lccs', type_='foreignkey')
    op.drop_constraint(op.f('styles_style_format_id_style_formats_fkey'), 'styles', schema='lccs', type_='foreignkey')
    op.create_foreign_key('styles_class_system_id_class_systems_fkey', 'styles', 'class_systems', ['class_system_id'], ['id'], source_schema='lccs', referent_schema='lccs')
    op.create_foreign_key('styles_style_format_id_style_formats_fkey', 'styles', 'style_formats', ['style_format_id'], ['id'], source_schema='lccs', referent_schema='lccs')
    op.drop_index(op.f('idx_lccs_styles_style_format_id'), table_name='styles', schema='lccs')
    op.drop_index(op.f('idx_lccs_styles_class_system_id'), table_name='styles', schema='lccs')
    op.drop_index(op.f('idx_lccs_style_formats_name'), table_name='style_formats', schema='lccs')
    op.drop_constraint(op.f('style_formats_name_key'), 'style_formats', schema='lccs', type_='unique')
    op.drop_constraint(op.f('classes_class_parent_id_classes_fkey'), 'classes', schema='lccs', type_='foreignkey')
    op.drop_constraint(op.f('classes_class_system_id_class_systems_fkey'), 'classes', schema='lccs', type_='foreignkey')
    op.create_foreign_key('classes_class_system_id_class_systems_fkey', 'classes', 'class_systems', ['class_system_id'], ['id'], source_schema='lccs', referent_schema='lccs')
    op.create_foreign_key('classes_class_parent_id_classes_fkey', 'classes', 'classes', ['class_parent_id'], ['id'], source_schema='lccs', referent_schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_name'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_code'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_class_system_id'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_class_systems_name'), table_name='class_systems', schema='lccs')
    op.drop_constraint(op.f('class_systems_name_key'), 'class_systems', schema='lccs', type_='unique')
    op.drop_constraint(op.f('class_mappings_target_class_id_classes_fkey'), 'class_mappings', schema='lccs', type_='foreignkey')
    op.drop_constraint(op.f('class_mappings_source_class_id_classes_fkey'), 'class_mappings', schema='lccs', type_='foreignkey')
    op.create_foreign_key('class_mappings_source_class_id_classes_fkey', 'class_mappings', 'classes', ['source_class_id'], ['id'], source_schema='lccs', referent_schema='lccs')
    op.create_foreign_key('class_mappings_target_class_id_classes_fkey', 'class_mappings', 'classes', ['target_class_id'], ['id'], source_schema='lccs', referent_schema='lccs')
    op.drop_index(op.f('idx_lccs_class_mappings_target_class_id'), table_name='class_mappings', schema='lccs')
    op.drop_index(op.f('idx_lccs_class_mappings_source_class_id'), table_name='class_mappings', schema='lccs')
    # ### end Alembic commands ###
