"""create classes view.

Revision ID: e8b12ba52665
Revises: 03d259000eac
Create Date: 2020-05-06 11:36:39.243865

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm.session import Session
from lccs_db.models import LucClass, LucClassificationSystem, ClassesView


# revision identifiers, used by Alembic.
revision = 'e8b12ba52665'
down_revision = '03d259000eac'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute("CREATE OR REPLACE VIEW {} AS " \
    "SELECT classes.id, classes.name, classes.description, classes.code, " \
    "class_systems.name  AS class_system_name, " \
    "parent_class.name AS class_parent_name " \
    "FROM {} AS classes " \
    "JOIN {} AS class_systems ON class_systems.id = classes.class_system_id " \
    "LEFT OUTER JOIN {} AS parent_class ON classes.class_parent_id = parent_class.id;".format( ClassesView.__table__, LucClass.__table__,
                                                        LucClassificationSystem.__table__, LucClass.__table__)

    )
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute('DROP VIEW {};'.format(ClassesView.__table__))
    session.commit()
    # ### end Alembic commands ###
