"""create table

Revision ID: 16e9d12b913c
Revises: 
Create Date: 2019-12-14 20:33:09.942713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e9d12b913c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA luc')

    op.create_table('classification_system',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_name', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='luc'
    )
    op.create_table('class',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('classification_system_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_system_id'], ['luc.classification_system.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['luc.class.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='luc'
    )
    op.create_table('class_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_class_id', sa.Integer(), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('degree_of_similarity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['source_class_id'], ['luc.class.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['target_class_id'], ['luc.class.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('source_class_id', 'target_class_id'),
    schema='luc'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_mapping', schema='luc')
    op.drop_table('class', schema='luc')
    op.drop_table('classification_system', schema='luc')

    op.execute('DROP SCHEMA luc')
    # ### end Alembic commands ###
