"""create initial tables

Revision ID: 439d9359bfd4
Revises: 
Create Date: 2020-02-06 15:40:49.212824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439d9359bfd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('CREATE SCHEMA lccs')

    op.create_table('class_systems',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('authority_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lccs'
    )
    op.create_table('classes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('class_system_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_system_id'], ['lccs.class_systems.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='lccs'
    )
    op.create_table('class_mappings',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_class_id', sa.Integer(), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('degree_of_similarity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['source_class_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['target_class_id'], ['lccs.classes.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('source_class_id', 'target_class_id'),
    schema='lccs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_mappings', schema='lccs')
    op.drop_table('classes', schema='lccs')
    op.drop_table('class_systems', schema='lccs')

    op.execute('DROP SCHEMA lccs')

    # ### end Alembic commands ###
