"""create initial tables

Revision ID: 64661056a272
Revises: 
Create Date: 2019-12-03 10:38:14.234619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64661056a272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA bdc')

    op.create_table('luc_classification_system',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_name', sa.Text(), nullable=False),
    sa.Column('system_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )
    op.create_table('luc_class',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('luc_classification_system_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['luc_classification_system_id'], ['bdc.luc_classification_system.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )
    op.create_table('class_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_class_id', sa.Integer(), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('degree_of_similarity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['source_class_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['target_class_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('source_class_id', 'target_class_id'),
    schema='bdc'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_mapping', schema='bdc')
    op.drop_table('luc_class', schema='bdc')
    op.drop_table('luc_classification_system', schema='bdc')

    op.execute('DROP SCHEMA bdc')
    # ### end Alembic commands ###
