"""create initial tables

Revision ID: ba6abc44e7ed
Revises: 
Create Date: 2019-11-27 14:45:44.178533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6abc44e7ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('CREATE SCHEMA bdc')

    op.create_table('luc_classification_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_name', sa.Text(), nullable=False),
    sa.Column('system_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )

    op.create_table('luc_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('luc_classification_system_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['luc_classification_system_id'], ['bdc.luc_classification_system.id'],
                            ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('luc_classification_system', schema='bdc')
    op.drop_table('luc_class', schema='bdc')

    op.execute('DROP SCHEMA bdc')
    # ### end Alembic commands ###
