"""adicionando mapping

Revision ID: c97c818ea83b
Revises: ba6abc44e7ed
Create Date: 2019-11-27 16:19:20.336430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97c818ea83b'
down_revision = 'ba6abc44e7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_mapping',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source_classification_sys_id', sa.Integer(), nullable=False),
                    sa.Column('target_classification_sys_id', sa.Integer(), nullable=False),
                    sa.Column('source_class_id', sa.Integer(), nullable=False),
                    sa.Column('target_class_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('degree_of_similarity', sa.Numeric(), nullable=False),
                    sa.ForeignKeyConstraint(['source_classification_sys_id'], ['bdc.luc_classification_system.id'],
                                            ondelete='NO ACTION'),
                    sa.ForeignKeyConstraint(['target_classification_sys_id'], ['bdc.luc_classification_system.id'],
                                            ondelete='NO ACTION'),
                    sa.ForeignKeyConstraint(['source_class_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
                    sa.ForeignKeyConstraint(['target_class_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='bdc'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_mapping', schema='bdc')
    # ### end Alembic commands ###
